# Generated by Django 4.2.6 on 2023-11-04 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_childrenshome_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='childrenshome',
            name='visit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visit',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visit',
            name='childrens_home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_visits', to='user.childrenshome'),
        ),
    ]
