# Generated by Django 4.2.6 on 2023-11-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_childrenshome_visit_visit_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childrenshome',
            name='needs_clothes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='childrenshome',
            name='needs_food',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='childrenshome',
            name='needs_hygiene_supplies',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='childrenshome',
            name='needs_money',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='donation',
            name='donated_item',
            field=models.CharField(blank=True, choices=[('clothes', 'Clothes'), ('hygiene', 'Hygiene Supplies'), ('food', 'Food'), ('money', 'Money')], max_length=20),
        ),
        migrations.AlterField(
            model_name='childrenshome',
            name='visit',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
